on:
  push:
    branches:
      - sam
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: deploy-to-aws
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-campr --s3-bucket github-actions-with-aws-sam-may-20223-test --capabilities CAPABILITY_IAM --region us-east-1 

      